name: Python calculator

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display environment information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"

    - name: Run unit tests
      run: pytest
           find . -type f -name "*.whl" -o -name "*.tar.gz"  # Search for Python artifacts

