name: Building testing

on:
  push:
    branches:
      - main
      - suparn
  pull_request:
    branches:
      - main
      - suparn

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Build // Installing Dependency
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest
