name: Python application Continous Integration

on:
  push:
    branches:  
             - main
             - suparnDev
             
  pull_request:
    branches:
             - main
             - suparnDev

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Add Operation
      run: |
        echo -e "1\n90\n67\n" | python calculator_f.py
    - name: Run Subtract Operation
      run: |
        echo -e "2\n56\n-78\n" | python calculator_f.py
    - name: Run Multiply Operation
      run: |
        echo -e "3\n4\n5\n" | python calculator_f.py
    - name: Run Divide Operation
      run: |
        echo -e "4\n97\n45\n" | python calculator_f.py    
      
  
    - name: Test with pytest
      run: |
        pytest









