name: Python application Continous Integration

on:
  push:
    branches:  
             - main
             - suparnDev
             
  pull_request:
    branches:
             - main
             - suparnDev

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Add Operation
      run: |
        echo -e "1\n4\n5\n" | python calculator_f.py
      # The above echo command simulates user input: 1 (for add), 4 (first number), 4 (second number), and "yes" to continue.
    - name: Run Subtract Operation
      run: |
        echo -e "2\n8\n4\nyes\n" | python calculator_f.py
      # The above echo command simulates user input: 1 (for add), 4 (first number), 4 (second number), and "yes" to continue.
    - name: Run Multiply Operation
      run: |
        echo -e "3\n5\n4\nyes\n" | python calculator_f.py
      # The above echo command simulates user input: 1 (for add), 4 (first number), 4 (second number), and "yes" to continue.
    - name: Run Divide Operation
      run: |
        echo -e "4\n9\n3\nyes\n" | python calculator_f.py
      # The above echo command simulates user input: 1 (for add), 4 (first number), 4 (second number), and "yes" to continue.

    - name: Test with pytest
      run: |
        pytest
