name: Release Workflow CI

on:
  push: 
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: refs/tags/v1.2.3
        release_name: Release1.2.3
        draft: false
        prerelease: false
        
      env:
        GITHUB_TOKEN: SPAT
