on:
  push:
    tags:
      - 'v*.*.*'

name: create release

jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SPAT }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Extract version number
        id: extract_version
        run: echo "VERSION=$(echo $GITHUB_REF | sed 's/^refs\/tags\///; s/^v\.//')" >> $GITHUB_ENV
