name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run release script
      run: |
        if [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} =~ ^refs/tags/v ]]; then
          ./your-release-script.sh ${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.APT }}
