name: Release Pipeline A1

on:
  push:
    tags:
      - 'v*..'  # Trigger the workflow on version tags (e.g., v1.0.0)

permissions:
  contents: write
  # Add other necessary permissions here, if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: pytest

    - name: Extract version from tag
      id: get_version
      run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
